services:
  bookings.api:
    image: ${DOCKER_REGISTRY-}bookingsapi
    build:
      context: .
      dockerfile: src/API/Bookings.Api/Dockerfile
    ports:
      - 5000:8080
      - 5001:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081


  bookings.database:
    image: postgres:latest
    container_name: bookings.database
    environment:
      - POSTGRES_DB=bookings
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  bookings.identity:
    image: quay.io/keycloak/keycloak:latest
    container_name: Bookings.Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - 18080:8080
      - "19090:9000"

  bookings.seq:
    image: datalust/seq:latest
    container_name: Bookings.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=admin 
      - SEQ_FIRSTRUN_ADMINPASSWORD=password  
    ports:
      - 5341:5341
      - 8081:80
  bookings.redis:
    image: redis:latest
    container_name: Bookings.Redis
    restart: always
    ports:
        - 6379:6379
