<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Bookings.Common.Application\Bookings.Common.Application.csproj" />
    <ProjectReference Include="..\..\Events\Bookings.Modules.Events.PublicApi\Bookings.Modules.Events.PublicApi.csproj" />
    <ProjectReference Include="..\Bookings.Modules.Ticketing.Domain\Bookings.Modules.Ticketing.Domain.csproj" />
  </ItemGroup>
</Project>
